// Suburb data for SEO pages
export interface SuburbData {
  slug: string;
  name: string;
  region: string;
  postcode: string;
  description: string;
}

export const sydneySuburbs: SuburbData[] = [
  {
    slug: "parramatta",
    name: "Parramatta",
    region: "Western Sydney",
    postcode: "2150",
    description: "Parramatta's premier leak repair specialists serving homes and businesses throughout the CBD and surrounding areas.",
  },
  {
    slug: "bondi",
    name: "Bondi",
    region: "Eastern Suburbs",
    postcode: "2026",
    description: "Expert shower and balcony leak repairs in Bondi. We understand the unique challenges of coastal properties.",
  },
  {
    slug: "manly",
    name: "Manly",
    region: "Northern Beaches",
    postcode: "2095",
    description: "Trusted leak repair services for Manly homes. Specialising in waterproofing solutions for beachside properties.",
  },
  {
    slug: "chatswood",
    name: "Chatswood",
    region: "North Shore",
    postcode: "2067",
    description: "Professional leak repairs in Chatswood. Serving apartments, townhouses and family homes across the North Shore.",
  },
  {
    slug: "cronulla",
    name: "Cronulla",
    region: "Sutherland Shire",
    postcode: "2230",
    description: "Cronulla's trusted leak repair experts. Protecting your property from water damage with proven solutions.",
  },
  {
    slug: "bankstown",
    name: "Bankstown",
    region: "South Western Sydney",
    postcode: "2200",
    description: "Quality leak repair services in Bankstown. Affordable solutions for residential and commercial properties.",
  },
  {
    slug: "liverpool",
    name: "Liverpool",
    region: "South Western Sydney",
    postcode: "2170",
    description: "Liverpool's leading leak repair company. Fast, reliable service with transparent pricing.",
  },
  {
    slug: "penrith",
    name: "Penrith",
    region: "Western Sydney",
    postcode: "2750",
    description: "Expert leak repairs throughout Penrith and the Blue Mountains foothills. Local expertise you can trust.",
  },
  {
    slug: "blacktown",
    name: "Blacktown",
    region: "Western Sydney",
    postcode: "2148",
    description: "Comprehensive leak repair services for Blacktown residents. Quality workmanship guaranteed.",
  },
  {
    slug: "ryde",
    name: "Ryde",
    region: "Northern Sydney",
    postcode: "2112",
    description: "Professional shower and balcony repairs in Ryde. Serving the local community with excellence.",
  },
  {
    slug: "hornsby",
    name: "Hornsby",
    region: "Upper North Shore",
    postcode: "2077",
    description: "Hornsby's preferred leak repair specialists. Expert solutions for Upper North Shore properties.",
  },
  {
    slug: "sutherland",
    name: "Sutherland",
    region: "Sutherland Shire",
    postcode: "2232",
    description: "Trusted leak repair services throughout the Sutherland Shire. Local experts, proven results.",
  },
  {
    slug: "randwick",
    name: "Randwick",
    region: "Eastern Suburbs",
    postcode: "2031",
    description: "Expert leak repairs in Randwick and surrounding Eastern Suburbs. Quality solutions since day one.",
  },
  {
    slug: "marrickville",
    name: "Marrickville",
    region: "Inner West",
    postcode: "2204",
    description: "Marrickville's go-to leak repair team. Specialising in heritage homes and modern apartments.",
  },
  {
    slug: "hurstville",
    name: "Hurstville",
    region: "St George",
    postcode: "2220",
    description: "Professional leak repair services in Hurstville. Protecting St George properties from water damage.",
  },
  {
    slug: "burwood",
    name: "Burwood",
    region: "Inner West",
    postcode: "2134",
    description: "Burwood's trusted leak repair experts. Serving homes and businesses throughout the Inner West.",
  },
  {
    slug: "strathfield",
    name: "Strathfield",
    region: "Inner West",
    postcode: "2135",
    description: "Quality leak repairs in Strathfield. Premium service for premium properties.",
  },
  {
    slug: "epping",
    name: "Epping",
    region: "Northern Sydney",
    postcode: "2121",
    description: "Expert leak repair solutions in Epping. Professional service for residential and strata properties.",
  },
  {
    slug: "castle-hill",
    name: "Castle Hill",
    region: "Hills District",
    postcode: "2154",
    description: "Castle Hill's leading leak repair company. Trusted by homeowners throughout the Hills District.",
  },
  {
    slug: "mosman",
    name: "Mosman",
    region: "Lower North Shore",
    postcode: "2088",
    description: "Premium leak repair services in Mosman. Discreet, professional solutions for prestige properties.",
  },
  {
    slug: "dee-why",
    name: "Dee Why",
    region: "Northern Beaches",
    postcode: "2099",
    description: "Expert shower and balcony leak repairs in Dee Why. Specialising in coastal property waterproofing across the Northern Beaches.",
  },
  {
    slug: "brookvale",
    name: "Brookvale",
    region: "Northern Beaches",
    postcode: "2100",
    description: "Professional leak repair services in Brookvale. Trusted waterproofing solutions for Northern Beaches homes and businesses.",
  },
  {
    slug: "neutral-bay",
    name: "Neutral Bay",
    region: "Lower North Shore",
    postcode: "2089",
    description: "Reliable shower and balcony leak repairs in Neutral Bay. Serving apartments and homes across the Lower North Shore.",
  },
  {
    slug: "kirribilli",
    name: "Kirribilli",
    region: "Lower North Shore",
    postcode: "2061",
    description: "Premium leak repair services in Kirribilli. Expert waterproofing for heritage and modern properties on the harbour.",
  },
  {
    slug: "leichhardt",
    name: "Leichhardt",
    region: "Inner West",
    postcode: "2040",
    description: "Trusted leak repair specialists in Leichhardt. Quality shower and balcony repairs for Inner West properties.",
  },
  {
    slug: "ashfield",
    name: "Ashfield",
    region: "Inner West",
    postcode: "2131",
    description: "Professional shower and balcony leak repairs in Ashfield. Affordable, reliable service throughout the Inner West.",
  },
  {
    slug: "concord",
    name: "Concord",
    region: "Inner West",
    postcode: "2137",
    description: "Expert leak repairs in Concord. Waterproofing solutions for family homes and strata buildings in the Canada Bay area.",
  },
  {
    slug: "drummoyne",
    name: "Drummoyne",
    region: "Inner West",
    postcode: "2047",
    description: "Quality leak repair services in Drummoyne. Protecting waterfront and heritage properties from water damage.",
  },
  {
    slug: "five-dock",
    name: "Five Dock",
    region: "Inner West",
    postcode: "2046",
    description: "Trusted shower and balcony leak repair specialists in Five Dock. Fast, professional service with a 10-year warranty.",
  },
  {
    slug: "gladesville",
    name: "Gladesville",
    region: "Northern Sydney",
    postcode: "2111",
    description: "Professional leak repairs in Gladesville. Serving homes and units throughout the Ryde and Hunters Hill area.",
  },
  {
    slug: "lane-cove",
    name: "Lane Cove",
    region: "Lower North Shore",
    postcode: "2066",
    description: "Expert shower and balcony repairs in Lane Cove. Quality waterproofing for North Shore apartments and houses.",
  },
  {
    slug: "lindfield",
    name: "Lindfield",
    region: "Upper North Shore",
    postcode: "2070",
    description: "Trusted leak repair services in Lindfield. Professional waterproofing solutions for Upper North Shore homes.",
  },
  {
    slug: "turramurra",
    name: "Turramurra",
    region: "Upper North Shore",
    postcode: "2074",
    description: "Expert leak repairs in Turramurra. Protecting your Upper North Shore property with proven waterproofing systems.",
  },
  {
    slug: "wahroonga",
    name: "Wahroonga",
    region: "Upper North Shore",
    postcode: "2076",
    description: "Premium shower and balcony leak repairs in Wahroonga. Trusted by homeowners across the Upper North Shore.",
  },
  {
    slug: "beecroft",
    name: "Beecroft",
    region: "Hills District",
    postcode: "2119",
    description: "Professional leak repair services in Beecroft. Expert waterproofing for homes in the Hills and North Shore corridor.",
  },
  {
    slug: "carlingford",
    name: "Carlingford",
    region: "Hills District",
    postcode: "2118",
    description: "Trusted leak repair specialists in Carlingford. Quality shower and balcony repairs with a 10-year warranty.",
  },
  {
    slug: "baulkham-hills",
    name: "Baulkham Hills",
    region: "Hills District",
    postcode: "2153",
    description: "Expert leak repairs in Baulkham Hills. Serving the Hills District with professional waterproofing solutions.",
  },
  {
    slug: "kellyville",
    name: "Kellyville",
    region: "Hills District",
    postcode: "2155",
    description: "Professional shower and balcony leak repairs in Kellyville. Trusted waterproofing for new and established homes.",
  },
  {
    slug: "rouse-hill",
    name: "Rouse Hill",
    region: "Hills District",
    postcode: "2155",
    description: "Reliable leak repair services in Rouse Hill. Expert solutions for the North West growth corridor.",
  },
  {
    slug: "campbelltown",
    name: "Campbelltown",
    region: "Macarthur",
    postcode: "2560",
    description: "Trusted leak repair specialists in Campbelltown. Affordable shower and balcony waterproofing across the Macarthur region.",
  },
  {
    slug: "camden",
    name: "Camden",
    region: "Macarthur",
    postcode: "2570",
    description: "Expert leak repairs in Camden. Protecting homes and new developments in Sydney's South West growth area.",
  },
  {
    slug: "kogarah",
    name: "Kogarah",
    region: "St George",
    postcode: "2217",
    description: "Professional shower and balcony repairs in Kogarah. Quality waterproofing for St George area properties.",
  },
  {
    slug: "rockdale",
    name: "Rockdale",
    region: "St George",
    postcode: "2216",
    description: "Trusted leak repair services in Rockdale. Expert solutions for apartments and homes in the St George district.",
  },
  {
    slug: "sans-souci",
    name: "Sans Souci",
    region: "St George",
    postcode: "2219",
    description: "Expert leak repairs in Sans Souci. Waterproofing specialists for bayside properties in the St George area.",
  },
  {
    slug: "miranda",
    name: "Miranda",
    region: "Sutherland Shire",
    postcode: "2228",
    description: "Professional shower and balcony leak repairs in Miranda. Trusted waterproofing solutions for the Sutherland Shire.",
  },
  {
    slug: "caringbah",
    name: "Caringbah",
    region: "Sutherland Shire",
    postcode: "2229",
    description: "Reliable leak repair services in Caringbah. Quality waterproofing for Sutherland Shire homes and units.",
  },
  {
    slug: "maroubra",
    name: "Maroubra",
    region: "Eastern Suburbs",
    postcode: "2035",
    description: "Expert shower and balcony leak repairs in Maroubra. Specialising in coastal property waterproofing in the Eastern Suburbs.",
  },
  {
    slug: "coogee",
    name: "Coogee",
    region: "Eastern Suburbs",
    postcode: "2034",
    description: "Premium leak repair services in Coogee. Protecting coastal properties from water damage with expert waterproofing.",
  },
  {
    slug: "double-bay",
    name: "Double Bay",
    region: "Eastern Suburbs",
    postcode: "2028",
    description: "Discreet, professional leak repair services in Double Bay. Premium waterproofing solutions for prestige Eastern Suburbs properties.",
  },
  {
    slug: "surry-hills",
    name: "Surry Hills",
    region: "Inner Sydney",
    postcode: "2010",
    description: "Trusted leak repair specialists in Surry Hills. Expert shower and balcony repairs for terraces, apartments, and heritage buildings.",
  },
  {
    slug: "redfern",
    name: "Redfern",
    region: "Inner Sydney",
    postcode: "2016",
    description: "Professional leak repair services in Redfern. Expert waterproofing for terraces, apartments, and mixed-use buildings in inner Sydney.",
  },
  {
    slug: "woolloomooloo",
    name: "Woolloomooloo",
    region: "Inner Sydney",
    postcode: "2011",
    description: "Trusted shower and balcony leak repairs in Woolloomooloo. Specialising in heritage and harbourside property waterproofing.",
  },
  {
    slug: "willoughby",
    name: "Willoughby",
    region: "North Shore",
    postcode: "2068",
    description: "Expert leak repair services in Willoughby. Professional waterproofing solutions for North Shore homes and strata buildings.",
  },
  {
    slug: "artarmon",
    name: "Artarmon",
    region: "North Shore",
    postcode: "2064",
    description: "Reliable shower and balcony leak repairs in Artarmon. Serving residential and commercial properties across the North Shore.",
  },
  {
    slug: "fairfield",
    name: "Fairfield",
    region: "South Western Sydney",
    postcode: "2165",
    description: "Affordable leak repair specialists in Fairfield. Quality shower and balcony waterproofing for South Western Sydney properties.",
  },
  {
    slug: "cabramatta",
    name: "Cabramatta",
    region: "South Western Sydney",
    postcode: "2166",
    description: "Professional leak repair services in Cabramatta. Trusted waterproofing solutions for homes and units in South Western Sydney.",
  },
  {
    slug: "ingleburn",
    name: "Ingleburn",
    region: "Macarthur",
    postcode: "2565",
    description: "Expert shower and balcony leak repairs in Ingleburn. Reliable waterproofing services throughout the Macarthur region.",
  },
  {
    slug: "narellan",
    name: "Narellan",
    region: "Macarthur",
    postcode: "2567",
    description: "Trusted leak repair specialists in Narellan. Protecting new and established homes in the Macarthur growth corridor.",
  },
];

export function getSuburbBySlug(slug: string): SuburbData | undefined {
  return sydneySuburbs.find((suburb) => suburb.slug === slug);
}

export function getAllSuburbSlugs(): string[] {
  return sydneySuburbs.map((suburb) => suburb.slug);
}
