// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esxbmiwtkaxvtibalptz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzeGJtaXd0a2F4dnRpYmFscHR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc1NTg2OTIsImV4cCI6MjA5MzEzNDY5Mn0.R_huIeu55fr1_u5gva6tn7fWI4k6dfo1G-4AOf50wcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});