// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://doyibwmeswkwiygyilqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRveWlid21lc3drd2l5Z3lpbHFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5MTIyNzksImV4cCI6MjA4ODQ4ODI3OX0.X9qvw35YD9UrijT2iFzISxLHrHFbBTxKdA48GcrSnMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});